name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.4, 14.13.0]

    steps:
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout repository
      uses: actions/checkout@v2.1.0

    - name: Install ESLint
      run: npm install -g eslint

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Run coverage
      run: npm run coveralls

    - name: Notify Slack
      if: always()
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: '${{ github.repository }} - Tests '
        channel: '#development'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'
